#include <cgen.h>
#include <lexer.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>

#define BUF_SIZE 2048

void emit_escaped_code(FILE *out, const char *code) {
    for (const char *p = code; *p; p++) {
        if (*p == '\\' && *(p + 1) == 'n') {
            fputc('\n', out);
            p++;
        } else {
            fputc(*p, out);
        }
    }
    fputc('\n', out);
}

int is_valid_reconf_file(const char *path) {
    struct stat st;

    if (stat(path, &st) != 0) {
        fprintf(stderr, "reconf: error: cannot access '%s': %s\n", path, strerror(errno));
        return 0;
    }

    if (S_ISDIR(st.st_mode)) {
        fprintf(stderr, "reconf: error: '%s' is a directory, not a configuration file\n", path);
        return 0;
    }

    if (!S_ISREG(st.st_mode)) {
        fprintf(stderr, "reconf: error: '%s' is not a regular file\n", path);
        return 0;
    }

    const char *ext = strrchr(path, '.');
    if (!ext || strcmp(ext, ".co") != 0) {
        fprintf(stderr, "reconf: warning: '%s' does not have a '.co' extension\n", path);
        // return 0;
    }

    return 1;
}


int generate_configure(const ProjectConfig *cfg, const char *out_path) {
    FILE *out = fopen(out_path, "w");
    if (!out) {
        perror("Could not create configure script");
        return -1;
    }

    fputs("#!/bin/sh\n", out);
    fputs("# Generated by reconf - configure script\n\n", out);

    const char *pname = cfg->pkg_name[0] ? cfg->pkg_name : "app";
    const char *pver  = cfg->pkg_version[0] ? cfg->pkg_version : "0.1.0";

    fprintf(out, "PACKAGE_NAME=\"%s\"\n", pname);
    fprintf(out, "PACKAGE_VERSION=\"%s\"\n", pver);

    /* Heap-allocated state buffers */
    char *target_so = malloc(256);
    char *target_a = malloc(256);
    char *target_bin = malloc(256);
    char *sources_raw = malloc(BUF_SIZE);
    char *obj_list = malloc(BUF_SIZE * 2);
    char *custom_libs_list = malloc(BUF_SIZE);

    if (!target_so || !target_a || !target_bin || !sources_raw || !obj_list || !custom_libs_list) {
        fclose(out);
        free(target_so);
        free(target_a);
        free(target_bin);
        free(sources_raw);
        free(obj_list);
        free(custom_libs_list);
        return -1;
    }

    memset(target_so, 0, 256);
    memset(target_a, 0, 256);
    memset(target_bin, 0, 256);
    memset(sources_raw, 0, BUF_SIZE);
    memset(obj_list, 0, BUF_SIZE * 2);
    memset(custom_libs_list, 0, BUF_SIZE);

    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type == TYPE_VAR) {
            fprintf(out, "%s=\"${%s:-%s}\"\n", it->name, it->name, it->arg1);
        } else if (it->type == TYPE_TARGET_SO) {
            size_t len = strlen(it->arg1);
            if (len >= 256) len = 255;
            memcpy(target_so, it->arg1, len);
            target_so[len] = '\0';
        } else if (it->type == TYPE_TARGET_A) {
            size_t len = strlen(it->arg1);
            if (len >= 256) len = 255;
            memcpy(target_a, it->arg1, len);
            target_a[len] = '\0';
        } else if (it->type == TYPE_TARGET_BIN) {
            size_t len = strlen(it->arg1);
            if (len >= 256) len = 255;
            memcpy(target_bin, it->arg1, len);
            target_bin[len] = '\0';
        } else if (it->type == TYPE_SOURCES) {
            size_t len = strlen(it->arg1);
            if (len >= BUF_SIZE) len = BUF_SIZE - 1;
            memcpy(sources_raw, it->arg1, len);
            sources_raw[len] = '\0';
        }
    }

    if (!target_so[0] && !target_a[0] && !target_bin[0]) {
        size_t len = strlen(pname);
        if (len >= 256) len = 255;
        memcpy(target_bin, pname, len);
        target_bin[len] = '\0';
    }

    fputs("CC=\"${CC:-gcc}\"\n", out);
    fputs("CFLAGS=\"${CFLAGS:--O2}\"\n", out);
    fputs("LDFLAGS=\"${LDFLAGS:-}\"\n\n", out);

    fputs("mkdir -p build/obj\n\n", out);

    fputs("rm -f build/config.h\n", out);
    fputs("echo \"/* Auto-generated by ./configure */\" > build/config.h\n", out);
    fputs("echo \"#ifndef CONFIG_H\" >> build/config.h\n", out);
    fputs("echo \"#define CONFIG_H\" >> build/config.h\n\n", out);

    fputs("printf \"Checking C compiler ($CC)... \"\n", out);
    fputs("if command -v \"$CC\" >/dev/null 2>&1; then echo \"yes\"; else echo \"no\"; exit 1; fi\n\n", out);

    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type == TYPE_HEADER) {
            fprintf(out, "printf \"Checking for <%s>... \"\n", it->arg1);
            fprintf(out, "cat << 'EOF' > _test.c\n");
            fprintf(out, "#include <%s>\n", it->arg1);
            fprintf(out, "int main(void){ return 0; }\n");
            fprintf(out, "EOF\n");
            fprintf(out, "if $CC $CFLAGS _test.c -o _test $LDFLAGS >/dev/null 2>&1; then\n");
            fprintf(out, "  echo \"yes\"; echo \"#define %s 1\" >> build/config.h\n", it->name);
            fprintf(out, "else\n");
            fprintf(out, "  echo \"no\"; echo \"#define %s 0\" >> build/config.h\n", it->name);
            fprintf(out, "fi\n");
            fprintf(out, "rm -f _test.c _test\n\n");
        } else if (it->type == TYPE_CODE) {
            fprintf(out, "printf \"Checking code snippet '%s'... \"\n", it->name);
            fprintf(out, "cat << 'EOF' > _test.c\n");
            emit_escaped_code(out, it->arg1);
            fprintf(out, "EOF\n");
            fprintf(out, "if $CC $CFLAGS _test.c -o _test $LDFLAGS >/dev/null 2>&1; then\n");
            fprintf(out, "  echo \"yes\"; echo \"#define %s 1\" >> build/config.h\n", it->name);
            fprintf(out, "else\n");
            fprintf(out, "  echo \"no\"; echo \"#define %s 0\" >> build/config.h\n", it->name);
            fprintf(out, "fi\n");
            fprintf(out, "rm -f _test.c _test\n\n");
        }
    }

    fputs("echo \"#endif\" >> build/config.h\n\n", out);

    /* Generate rules.ninja */
    fputs("cat << 'EOF' > build/rules.ninja\n", out);
    fputs("rule compile\n", out);
    fputs("  command = $CC $CFLAGS $INCLUDES -I../include -I.. -I. -MF $out.d -MMD -MP -c $in -o $out\n", out);
    fputs("  depfile = $out.d\n", out);
    fputs("  deps = gcc\n", out);
    fputs("  description = Compiling $out\n\n", out);

    fputs("rule link_bin\n", out);
    fputs("  command = $CC -o $out $in $LDFLAGS\n", out);
    fputs("  description = Linking binary $out\n\n", out);

    fputs("rule link_shared\n", out);
    fputs("  command = $CC -shared -o $out $in $LDFLAGS\n", out);
    fputs("  description = Linking $out\n\n", out);

    fputs("rule link_static\n", out);
    fputs("  command = ar rcs $out $in\n", out);
    fputs("  description = Linking $out\n\n", out);

    fputs("rule custom_cmd\n", out);
    fputs("  command = $cmd\n", out);
    fputs("  description = Running custom rule: $out\n\n", out);

    fputs("EOF\n\n", out);

    /* Generate build.ninja */
    fputs("cat << EOF > build/build.ninja\n", out);
    fputs("include rules.ninja\n\n", out);
    fprintf(out, "CC = %s\n", "$CC");
    fprintf(out, "CFLAGS = %s\n", "$CFLAGS");
    fprintf(out, "INCLUDES = %s\n\n", "$INCLUDES");
    fprintf(out, "LDFLAGS = %s\n\n", "$LDFLAGS");

    /* Handle custom library build targets (e.g., TYPE_CUSTOM_LIB) */
    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type == TYPE_CUSTOM_LIB) {
            fprintf(out, "build %s: custom_cmd\n", it->name);
            fprintf(out, "  cmd = %s\n\n", it->arg1);

            strcat(custom_libs_list, " ");
            strcat(custom_libs_list, it->name);
        }
    }

    size_t n = strlen(sources_raw) + 1;
    char *src_copy = malloc(n);
    if (!src_copy) {
        fclose(out);
        free(target_so);
        free(target_a);
        free(target_bin);
        free(sources_raw);
        free(obj_list);
        free(custom_libs_list);
        return -1;
    }
    memcpy(src_copy, sources_raw, n);

    char *token = strtok(src_copy, " \t\r\n");
    char *base = malloc(256);
    char *obj_path = malloc(512);

    if (!base || !obj_path) {
        fclose(out);
        free(target_so);
        free(target_a);
        free(target_bin);
        free(sources_raw);
        free(obj_list);
        free(custom_libs_list);
        free(src_copy);
        free(base);
        free(obj_path);
        return -1;
    }

    while (token) {
        if (strlen(token) > 0) {
            get_basename(token, base);

            char *dot = strrchr(base, '.');
            if (dot) *dot = '\0';

            snprintf(obj_path, 512, "obj/%s.o", base);

            fprintf(out, "build %s: compile ../%s\n", obj_path, token);

            strcat(obj_list, " ");
            strcat(obj_list, obj_path);
        }
        token = strtok(NULL, " \t\r\n");
    }

    free(src_copy);
    free(base);
    free(obj_path);

    fputs("\n", out);
    if (target_bin[0]) {
        /* Binaries depend on compiled object files AND custom sub-libraries */
        fprintf(out, "build %s: link_bin%s%s\n", target_bin, obj_list, custom_libs_list);
    }
    if (target_so[0]) {
        fprintf(out, "build %s: link_shared%s%s\n", target_so, obj_list, custom_libs_list);
    }
    if (target_a[0]) {
        fprintf(out, "build %s: link_static%s%s\n", target_a, obj_list, custom_libs_list);
    }

    fprintf(out, "\ndefault");
    if (target_bin[0]) fprintf(out, " %s", target_bin);
    if (target_so[0])  fprintf(out, " %s", target_so);
    if (target_a[0])   fprintf(out, " %s", target_a);
    fputs("\n", out);

    fputs("EOF\n\n", out);

    fputs("echo \"Configuration complete. Run 'ninja -C build' to build.\"\n", out);

    free(target_so);
    free(target_a);
    free(target_bin);
    free(sources_raw);
    free(obj_list);
    free(custom_libs_list);

    fclose(out);
    chmod(out_path, 0755);
    return 0;
}
