#define _POSIX_C_SOURCE 200809L

#include <cgen.h>
#include <lexer.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>

#define BUF_SIZE 8192

void emit_escaped_code(FILE *out, const char *code) {
    for (const char *p = code; *p; p++) {
        if (*p == '\\' && *(p + 1) == 'n') {
            fputc('\n', out);
            p++;
        } else {
            fputc(*p, out);
        }
    }
    fputc('\n', out);
}

int is_valid_reconf_file(const char *path) {
    struct stat st;

    if (stat(path, &st) != 0) {
        fprintf(stderr, "reconf: error: cannot access '%s': %s\n", path, strerror(errno));
        return 0;
    }

    if (S_ISDIR(st.st_mode)) {
        fprintf(stderr, "reconf: error: '%s' is a directory, not a configuration file\n", path);
        return 0;
    }

    if (!S_ISREG(st.st_mode)) {
        fprintf(stderr, "reconf: error: '%s' is not a regular file\n", path);
        return 0;
    }

    const char *ext = strrchr(path, '.');
    if (!ext || strcmp(ext, ".co") != 0) {
        fprintf(stderr, "reconf: warning: '%s' does not have a '.co' extension\n", path);
    }

    return 1;
}

int generate_configure(const ProjectConfig *cfg, const char *out_path) {
    FILE *out = fopen(out_path, "w");
    if (!out) {
        perror("Could not create configure script");
        return -1;
    }

    fputs("#!/bin/sh\n", out);
    fputs("# Generated by reconf - configure script\n\n", out);

    const char *pname = cfg->pkg_name[0] ? cfg->pkg_name : "app";
    const char *pver  = cfg->pkg_version[0] ? cfg->pkg_version : "0.1.0";

    fprintf(out, "PACKAGE_NAME=\"%s\"\n", pname);
    fprintf(out, "PACKAGE_VERSION=\"%s\"\n", pver);

    char *custom_libs_list = calloc(1, BUF_SIZE);
    if (!custom_libs_list) {
        fclose(out);
        return -1;
    }

    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type == TYPE_VAR) {
            fprintf(out, "%s=\"${%s:-%s}\"\n", it->name, it->name, it->arg1);
        }
    }

    fputs("CC=\"${CC:-gcc}\"\n", out);
    fputs("CFLAGS=\"${CFLAGS:--O2}\"\n", out);
    fputs("LDFLAGS=\"${LDFLAGS:-}\"\n\n", out);

    fputs("mkdir -p build/obj\n\n", out);

    fputs("rm -f build/config.h\n", out);
    fputs("echo \"/* Auto-generated by ./configure */\" > build/config.h\n", out);
    fputs("echo \"#ifndef CONFIG_H\" >> build/config.h\n", out);
    fputs("echo \"#define CONFIG_H\" >> build/config.h\n\n", out);

    fputs("printf \"Checking C compiler ($CC)... \"\n", out);
    fputs("if command -v \"$CC\" >/dev/null 2>&1; then echo \"yes\"; else echo \"no\"; exit 1; fi\n\n", out);

    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type == TYPE_HEADER) {
            fprintf(out, "printf \"Checking for <%s>... \"\n", it->arg1);
            fprintf(out, "if printf '#include <%s>\\n' | $CC $CFLAGS $INCLUDES -MF /dev/null -E - >/dev/null 2>&1; then\n", it->arg1);
            fprintf(out, "  echo \"yes\"\n");
            fprintf(out, "  echo \"#define %s 1\" >> build/config.h\n", it->name);
            fprintf(out, "else\n");
            fprintf(out, "  echo \"no\"\n");
            fprintf(out, "  echo \"#define %s 0\" >> build/config.h\n", it->name);
            fprintf(out, "fi\n\n");
        } else if (it->type == TYPE_CODE) {
            fprintf(out, "printf \"Checking code snippet '%s'... \"\n", it->name);
            fprintf(out, "cat << 'EOF' > _test.c\n");
            emit_escaped_code(out, it->arg1);
            fprintf(out, "EOF\n");
            fprintf(out, "if $CC $CFLAGS _test.c -o _test $LDFLAGS >/dev/null 2>&1; then\n");
            fprintf(out, "  echo \"yes\"; echo \"#define %s 1\" >> build/config.h\n", it->name);
            fprintf(out, "else\n");
            fprintf(out, "  echo \"no\"; echo \"#define %s 0\" >> build/config.h\n", it->name);
            fprintf(out, "fi\n");
            fprintf(out, "rm -f _test.c _test\n\n");
        }
    }

    fputs("echo \"#endif\" >> build/config.h\n\n", out);

    /* Generate rules.ninja */
    fputs("cat << 'EOF' > build/rules.ninja\n", out);
    fputs("rule compile\n", out);
    fputs("  command = $CC $CFLAGS $INCLUDES -I../include -I.. -I. -MF $out.d -MMD -MP -c $in -o $out\n", out);
    fputs("  depfile = $out.d\n", out);
    fputs("  deps = gcc\n", out);
    fputs("  description = Compiling $out\n\n", out);

    fputs("rule link_bin\n", out);
    fputs("  command = $CC -o $out $in $LDFLAGS\n", out);
    fputs("  description = Linking binary $out\n\n", out);

    fputs("rule link_shared\n", out);
    fputs("  command = $CC -shared -o $out $in $LDFLAGS\n", out);
    fputs("  description = Linking $out\n\n", out);

    fputs("rule link_static\n", out);
    fputs("  command = ar rcs $out $in\n", out);
    fputs("  description = Linking $out\n\n", out);

    fputs("rule custom_cmd\n", out);
    fputs("  command = $cmd\n", out);
    fputs("  description = Building dependency $out (please wait...)\n\n", out);

    fputs("EOF\n\n", out);

    /* Generate build.ninja */
    fputs("cat << EOF > build/build.ninja\n", out);
    fputs("include rules.ninja\n\n", out);
    fprintf(out, "CC = %s\n", "$CC");
    fprintf(out, "CFLAGS = %s\n", "$CFLAGS");
    fprintf(out, "INCLUDES = %s\n", "$INCLUDES");
    fprintf(out, "LDFLAGS = %s\n\n", "$LDFLAGS");

    /* Custom sub-libraries */
    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type == TYPE_CUSTOM_LIB) {
            fprintf(out, "build %s: custom_cmd\n", it->name);
            fprintf(out, "  cmd = %s\n\n", it->arg1);
            strncat(custom_libs_list, " ", BUF_SIZE - strlen(custom_libs_list) - 1);
            strncat(custom_libs_list, it->name, BUF_SIZE - strlen(custom_libs_list) - 1);
        }
    }

    char *target_names[MAX_ITEMS];
    int target_count = 0;

    /* Build rules for targets */
    for (int i = 0; i < cfg->item_count; i++) {
        const ConfigItem *it = &cfg->items[i];
        if (it->type != TYPE_TARGET_BIN && it->type != TYPE_TARGET_SO && it->type != TYPE_TARGET_A) {
            continue;
        }

        const char *tgt_name = it->arg1;
        target_names[target_count++] = (char *)tgt_name;

        char obj_list[BUF_SIZE] = "";

        if (it->target_sources[0] != '\0') {
            char *src_copy = strdup(it->target_sources);
            char *token = strtok(src_copy, " \t\r\n");
            char base[256];
            char obj_path[512];

            while (token) {
                if (strlen(token) > 0) {
                    get_basename(token, base);
                    char *dot = strrchr(base, '.');
                    if (dot) *dot = '\0';

                    snprintf(obj_path, sizeof(obj_path), "obj/%s_%s.o", tgt_name, base);
                    fprintf(out, "build %s: compile ../%s\n", obj_path, token);

                    strncat(obj_list, " ", sizeof(obj_list) - strlen(obj_list) - 1);
                    strncat(obj_list, obj_path, sizeof(obj_list) - strlen(obj_list) - 1);
                }
                token = strtok(NULL, " \t\r\n");
            }
            free(src_copy);
        }

        fputs("\n", out);
        if (it->type == TYPE_TARGET_BIN) {
            fprintf(out, "build %s: link_bin%s%s\n", tgt_name, obj_list, custom_libs_list);
        } else if (it->type == TYPE_TARGET_SO) {
            fprintf(out, "build %s: link_shared%s%s\n", tgt_name, obj_list, custom_libs_list);
        } else if (it->type == TYPE_TARGET_A) {
            fprintf(out, "build %s: link_static%s%s\n", tgt_name, obj_list, custom_libs_list);
        }
        fputs("\n", out);
    }

    fprintf(out, "default");
    for (int i = 0; i < target_count; i++) {
        fprintf(out, " %s", target_names[i]);
    }
    fputs("\n", out);

    fputs("EOF\n\n", out);
    fputs("echo \"Configuration complete. Run 'ninja -C build' to build.\"\n", out);

    free(custom_libs_list);
    fclose(out);
    chmod(out_path, 0755);
    return 0;
}
